apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zot
  namespace: zot
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`zot.pangarabbit.com`)
      kind: Rule
      services:
        - name: zot
          namespace: zot
          port: 5000
  # tls:
  #   certResolver: default
